os: linux
language: node_js
cache: yarn
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn
  - yarn global add codecov
script:
  - yarn run test
  - yarn run lint
after_success:
  - codecov
notifications:
  email:
    on_failure: always
    on_success: change