language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
node_js:
  - "lts/*"
  - "stable"
  - "node"
  - "7"
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - yarn
script:
  - yarn run test
  - yarn run lint
